# Set SSH credentials for scm and the server
credentials:
  system:
    domainCredentials:
      - credentials:
         - basicSSHUserPrivateKey:
              scope: "GLOBAL"
              id: "scmKey"
              username: "${SECRET_SCM_USERNAME}"
              passphrase: "${SECRET_SCM_PASSPHRASE}"
              description: "SCM SSH key"
              privateKeySource:
                directEntry:
                  privateKey: "${scmSSHKey}" # Docker secret
         - basicSSHUserPrivateKey:
              scope: "GLOBAL"
              id: "sshServerKey"
              username: "${SECRET_SERVER_USERNAME}"
              passphrase: "${SECRET_SERVER_PASSPHRASE"
              description: "Server SSH key"
              privateKeySource:
                directEntry:
                  privateKey: "${serverSSHKey}" # Docker secret
              - credentials:
         - string:
            id: "webhookToken"
            scope: GLOBAL
            secret: "${SECRET_WEBHOOK_TOKEN}"